// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_rtc.proto

package com.freckles.of.couple.fubble.grpc;

public final class RtcMessageContainer {
    private RtcMessageContainer() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface JoinRoomRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:server.JoinRoomRequest)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>optional string id = 1;</code>
         */
        java.lang.String getId();

        /**
         * <code>optional string id = 1;</code>
         */
        com.google.protobuf.ByteString getIdBytes();
    }

    /**
     * Protobuf type {@code server.JoinRoomRequest}
     */
    public static final class JoinRoomRequest extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:server.JoinRoomRequest)
        JoinRoomRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use JoinRoomRequest.newBuilder() to construct.
        private JoinRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private JoinRoomRequest() {
            id_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private JoinRoomRequest(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            id_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_JoinRoomRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_JoinRoomRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.class,
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.Builder.class);
        }

        private int                       bitField0_;
        public static final int           ID_FIELD_NUMBER = 1;
        private volatile java.lang.Object id_;

        /**
         * <code>optional string id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string id = 1;</code>
         */
        public java.lang.String getId() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    id_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string id = 1;</code>
         */
        public com.google.protobuf.ByteString getIdBytes() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest)) {
                return super.equals(obj);
            }
            com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest other = (com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest) obj;

            boolean result = true;
            result = result && (hasId() == other.hasId());
            if (hasId()) {
                result = result && getId().equals(other.getId());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasId()) {
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + getId().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code server.JoinRoomRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:server.JoinRoomRequest)
            com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_JoinRoomRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_JoinRoomRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.class,
                    com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.Builder.class);
            }

            // Construct using com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_JoinRoomRequest_descriptor;
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest getDefaultInstanceForType() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.getDefaultInstance();
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest build() {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest buildPartial() {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest result = new com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest(
                    this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest) {
                    return mergeFrom((com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest other) {
                if (other == com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest.getDefaultInstance())
                    return this;
                if (other.hasId()) {
                    bitField0_ |= 0x00000001;
                    id_ = other.id_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int              bitField0_;

            private java.lang.Object id_ = "";

            /**
             * <code>optional string id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public java.lang.String getId() {
                java.lang.Object ref = id_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        id_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public com.google.protobuf.ByteString getIdBytes() {
                java.lang.Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public Builder setId(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public Builder setIdBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:server.JoinRoomRequest)
        }

        // @@protoc_insertion_point(class_scope:server.JoinRoomRequest)
        private static final com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest();
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<JoinRoomRequest> PARSER = new com.google.protobuf.AbstractParser<JoinRoomRequest>() {
            public JoinRoomRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new JoinRoomRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<JoinRoomRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<JoinRoomRequest> getParserForType() {
            return PARSER;
        }

        public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.JoinRoomRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface RoomInformationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:server.RoomInformation)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string rtc_server = 1;</code>
         */
        boolean hasRtcServer();

        /**
         * <code>optional string rtc_server = 1;</code>
         */
        java.lang.String getRtcServer();

        /**
         * <code>optional string rtc_server = 1;</code>
         */
        com.google.protobuf.ByteString getRtcServerBytes();
    }

    /**
     * Protobuf type {@code server.RoomInformation}
     */
    public static final class RoomInformation extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:server.RoomInformation)
        RoomInformationOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use RoomInformation.newBuilder() to construct.
        private RoomInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RoomInformation() {
            rtcServer_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private RoomInformation(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            rtcServer_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_RoomInformation_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_RoomInformation_fieldAccessorTable.ensureFieldAccessorsInitialized(
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.class,
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.Builder.class);
        }

        private int                       bitField0_;
        public static final int           RTC_SERVER_FIELD_NUMBER = 1;
        private volatile java.lang.Object rtcServer_;

        /**
         * <code>optional string rtc_server = 1;</code>
         */
        public boolean hasRtcServer() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string rtc_server = 1;</code>
         */
        public java.lang.String getRtcServer() {
            java.lang.Object ref = rtcServer_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    rtcServer_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string rtc_server = 1;</code>
         */
        public com.google.protobuf.ByteString getRtcServerBytes() {
            java.lang.Object ref = rtcServer_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                rtcServer_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rtcServer_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rtcServer_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation)) {
                return super.equals(obj);
            }
            com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation other = (com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation) obj;

            boolean result = true;
            result = result && (hasRtcServer() == other.hasRtcServer());
            if (hasRtcServer()) {
                result = result && getRtcServer().equals(other.getRtcServer());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasRtcServer()) {
                hash = (37 * hash) + RTC_SERVER_FIELD_NUMBER;
                hash = (53 * hash) + getRtcServer().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code server.RoomInformation}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:server.RoomInformation)
            com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformationOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_RoomInformation_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_RoomInformation_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.class,
                    com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.Builder.class);
            }

            // Construct using com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                rtcServer_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_RoomInformation_descriptor;
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation getDefaultInstanceForType() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.getDefaultInstance();
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation build() {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation buildPartial() {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation result = new com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation(
                    this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.rtcServer_ = rtcServer_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation) {
                    return mergeFrom((com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation other) {
                if (other == com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation.getDefaultInstance())
                    return this;
                if (other.hasRtcServer()) {
                    bitField0_ |= 0x00000001;
                    rtcServer_ = other.rtcServer_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int              bitField0_;

            private java.lang.Object rtcServer_ = "";

            /**
             * <code>optional string rtc_server = 1;</code>
             */
            public boolean hasRtcServer() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string rtc_server = 1;</code>
             */
            public java.lang.String getRtcServer() {
                java.lang.Object ref = rtcServer_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        rtcServer_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string rtc_server = 1;</code>
             */
            public com.google.protobuf.ByteString getRtcServerBytes() {
                java.lang.Object ref = rtcServer_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    rtcServer_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string rtc_server = 1;</code>
             */
            public Builder setRtcServer(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                rtcServer_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string rtc_server = 1;</code>
             */
            public Builder clearRtcServer() {
                bitField0_ = (bitField0_ & ~0x00000001);
                rtcServer_ = getDefaultInstance().getRtcServer();
                onChanged();
                return this;
            }

            /**
             * <code>optional string rtc_server = 1;</code>
             */
            public Builder setRtcServerBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                rtcServer_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:server.RoomInformation)
        }

        // @@protoc_insertion_point(class_scope:server.RoomInformation)
        private static final com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation();
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<RoomInformation> PARSER = new com.google.protobuf.AbstractParser<RoomInformation>() {
            public RoomInformation parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new RoomInformation(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RoomInformation> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RoomInformation> getParserForType() {
            return PARSER;
        }

        public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.RoomInformation getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface DeleteRoomRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:server.DeleteRoomRequest)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>optional string id = 1;</code>
         */
        java.lang.String getId();

        /**
         * <code>optional string id = 1;</code>
         */
        com.google.protobuf.ByteString getIdBytes();
    }

    /**
     * Protobuf type {@code server.DeleteRoomRequest}
     */
    public static final class DeleteRoomRequest extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:server.DeleteRoomRequest)
        DeleteRoomRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use DeleteRoomRequest.newBuilder() to construct.
        private DeleteRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DeleteRoomRequest() {
            id_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private DeleteRoomRequest(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            id_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_DeleteRoomRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_DeleteRoomRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.class,
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.Builder.class);
        }

        private int                       bitField0_;
        public static final int           ID_FIELD_NUMBER = 1;
        private volatile java.lang.Object id_;

        /**
         * <code>optional string id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string id = 1;</code>
         */
        public java.lang.String getId() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    id_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string id = 1;</code>
         */
        public com.google.protobuf.ByteString getIdBytes() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest)) {
                return super.equals(obj);
            }
            com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest other = (com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest) obj;

            boolean result = true;
            result = result && (hasId() == other.hasId());
            if (hasId()) {
                result = result && getId().equals(other.getId());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasId()) {
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + getId().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code server.DeleteRoomRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:server.DeleteRoomRequest)
            com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_DeleteRoomRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_DeleteRoomRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.class,
                    com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.Builder.class);
            }

            // Construct using com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.internal_static_server_DeleteRoomRequest_descriptor;
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest getDefaultInstanceForType() {
                return com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.getDefaultInstance();
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest build() {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest buildPartial() {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest result = new com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest(
                    this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest) {
                    return mergeFrom((com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest other) {
                if (other == com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest.getDefaultInstance())
                    return this;
                if (other.hasId()) {
                    bitField0_ |= 0x00000001;
                    id_ = other.id_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int              bitField0_;

            private java.lang.Object id_ = "";

            /**
             * <code>optional string id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public java.lang.String getId() {
                java.lang.Object ref = id_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        id_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public com.google.protobuf.ByteString getIdBytes() {
                java.lang.Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public Builder setId(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string id = 1;</code>
             */
            public Builder setIdBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:server.DeleteRoomRequest)
        }

        // @@protoc_insertion_point(class_scope:server.DeleteRoomRequest)
        private static final com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest();
        }

        public static com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<DeleteRoomRequest> PARSER = new com.google.protobuf.AbstractParser<DeleteRoomRequest>() {
            public DeleteRoomRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new DeleteRoomRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DeleteRoomRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DeleteRoomRequest> getParserForType() {
            return PARSER;
        }

        public com.freckles.of.couple.fubble.grpc.RtcMessageContainer.DeleteRoomRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_server_JoinRoomRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_server_JoinRoomRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_server_RoomInformation_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_server_RoomInformation_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_server_DeleteRoomRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_server_DeleteRoomRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\rweb_rtc.proto\022\006server\032\033google/protobuf"
            + "/empty.proto\"\035\n\017JoinRoomRequest\022\n\n\002id\030\001 " + "\001(\t\"%\n\017RoomInformation\022\022\n\nrtc_server\030\001 \001"
            + "(\t\"\037\n\021DeleteRoomRequest\022\n\n\002id\030\001 \001(\t2\210\001\n\003"
            + "Rtc\022>\n\010JoinRoom\022\027.server.JoinRoomRequest" + "\032\027.server.RoomInformation\"\000\022A\n\nDeleteRoo"
            + "m\022\031.server.DeleteRoomRequest\032\026.google.pr" + "otobuf.Empty\"\000B9\n\"com.freckles.of.couple"
            + ".fubble.grpcB\023RtcMessageContainer" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] { com.google.protobuf.EmptyProto.getDescriptor(), }, assigner);
        internal_static_server_JoinRoomRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_server_JoinRoomRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_server_JoinRoomRequest_descriptor, new java.lang.String[] { "Id", });
        internal_static_server_RoomInformation_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_server_RoomInformation_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_server_RoomInformation_descriptor, new java.lang.String[] { "RtcServer", });
        internal_static_server_DeleteRoomRequest_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_server_DeleteRoomRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_server_DeleteRoomRequest_descriptor, new java.lang.String[] { "Id", });
        com.google.protobuf.EmptyProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
