
include:
  - local: '/web/landing/.gitlab-ci.yml'

build debug:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v0
  stage: build
  services:
    - docker:dind
  variables:
    FUBBLE_TREAT_WARNING_AS_ERROR: 0
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    - ./scripts/ci/build_debug
  after_script:
    - mv -v ../fubble_build/meson/meson-logs/testlog.txt .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

