stages:
  - build
  - package
  - deploy

test_rtc_session_handler:
  stage: build
  image: registry.gitlab.com/acof/fubble/ci/build_build:v0
  script: ./web/rtc/session_handler/scripts/ci/test

build_rtc_session_handler:
  stage: build
  image: registry.gitlab.com/acof/fubble/ci/build_build:v0
  script: ./web/rtc/session_handler/scripts/build_server
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
    - ./web/rtc/session_handler/dist/

package_rtc_session_handler:
  stage: package
  dependencies:
  - build_rtc_session_handler
  image: docker:stable
  services:
  - docker:dind
  script:
  - ./web/rtc/session_handler/scripts/ci/make_package

deploy_rtc_session_handler:
  stage: deploy
  image: ubuntu:18.04
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ./ci/deploy/install_ssh_keys
    - ./web/rtc/session_handler/scripts/ci/deploy/server

build_backend:
  stage: build
  image: maven:latest
  artifacts: 
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - web/backend/FubbleBackend/target/FubbleBackend.war
  script:
    - cd web/backend/FubbleBackend
    - mvn install -q -B

