stages:
  - build
  - package
  - deploy

build ubuntu_18.04 release:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v2
  tags:
    - linux
    - dedicated
  stage: build
  # services:
  #   - docker:dind
  variables:
    # DOCKER_HOST: "tcp://docker:2375"
    # DOCKER_DRIVER: "overlay2"
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    - ccache -s
    - git describe
    - ./scripts/ci/build_release
  after_script:
    # - rm -r ./deploy/development/install
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

build mac release:
  tags:
    - macos
  stage: build
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    - >
      python3 scripts/make_build.py
      --profile scripts/conan_profiles/mac_release
      --skip_export
  after_script:
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always


.build ios: &build_ios
  tags:
    - macos
  stage: build
  after_script:
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ./install*
      - ./meson-logs

.build ios debug:
  <<: *build_ios
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install_ios_debug
  script:
    - >
      python3 scripts/make_build.py
      --profile_build scripts/conan_profiles/mac_release
      --profile_host scripts/conan_profiles/ios_debug
      --skip_export
      --skip_qt

.build ios simulator debug:
  <<: *build_ios
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install_ios_simulator_debug
  script:
    - >
      python3 scripts/make_build.py
      --profile_build scripts/conan_profiles/mac_release
      --profile_host scripts/conan_profiles/ios_simulator_debug
      --skip_export
      --skip_qt

build ios release:
  <<: *build_ios
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install_ios_release
  script:
    - >
      python3 scripts/make_build.py
      --profile_build scripts/conan_profiles/mac_release
      --profile_host scripts/conan_profiles/ios_release
      --skip_export
      --skip_qt
  when: manual

build ios simulator release:
  <<: *build_ios
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install_ios_simulator_release
  script:
    - >
      python3 scripts/make_build.py
      --profile_build scripts/conan_profiles/mac_release
      --profile_host scripts/conan_profiles/ios_simulator_release
      --skip_export
      --skip_qt
  when: manual

.bundle ios: &bundle_ios
  tags:
    - macos
  stage: package
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ./fubble.framework

.package ios debug:
  <<: *bundle_ios
  needs:
    - build ios debug
    - build ios simulator debug
  script:
    - ./scripts/bundle_framework_ios_debug

# does not work due to 'build ios * release' being manual. pipline gets stuck
.package ios release:
  <<: *bundle_ios
  needs:
    - build ios release
    - build ios simulator release
  script:
    - ./scripts/bundle_framework_ios_release

appimage:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v2
  stage: package
  needs:
    - build ubuntu_18.04 release
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    # extend ./scripts/install_qt.py to do this
    - aqt install --outputdir /qt 5.15.1 linux desktop -m qtcharts
    - export PATH="/qt/5.15.1/gcc_64/bin:${PATH}"
    - ./scripts/ci/package_appimage
  artifacts:
    paths:
      - ./Fubble*.AppImage*
    expire_in: 1 week

.build windows: &build_windows
  stage: build
  tags:
    - windows
    - dedicated
  variables:
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install_windows
  before_script:
    - choco install -y --no-progress python pkgconfiglite cmake --installargs 'ADD_CMAKE_TO_PATH=System'
    # - refreshenv # did not work
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    - python --version
    - pip install --upgrade conan aqtinstall
    - python scripts/install_qt.py
    - conan --version
  after_script:
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

build windows release:
  <<: *build_windows
  script:
    - >
      python scripts/make_build.py
      --profile scripts/conan_profiles/windows_release
      --skip_export

build windows debug:
  <<: *build_windows
  script:
    - >
      python scripts/make_build.py
      --profile scripts/conan_profiles/windows_debug
      --skip_export
  when: manual

deploy services:
  stage: deploy
  image: registry.gitlab.com/acof/fubble-deploy/ansible_deploy:latest
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  when: manual
  needs:
    - build ubuntu_18.04 release
    - appimage
    - build windows release
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$FUBBLE_SSH_KEY")
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/acof/fubble-deploy.git deploy
  script:
    - ./scripts/deploy.py


