stages:
  - build
  - package

include:
  - local: '/web/landing/.gitlab-ci.yml'

build ubuntu_18.04 release:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v0
  stage: build
  # services:
  #   - docker:dind
  variables:
    # DOCKER_HOST: "tcp://docker:2375"
    # DOCKER_DRIVER: "overlay2"
    FUBBLE_TREAT_WARNING_AS_ERROR: 0
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    - ./scripts/ci/build_debug
  after_script:
    - rm -r ./deploy/development/install
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

appimage:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v0
  stage: package
  dependencies:
    - build ubuntu_18.04 release
  variables:
    QML_SOURCES_PATHS: ${CI_PROJECT_DIR}/client/app
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  before_script:
    - apt-get update
    - apt-get install fuse qml-module-qtquick-\* qml-module-qt-labs-\* \
        qml-module-qtcharts qml-module-qtmultimedia \
        qtdeclarative5-dev-tools
    - curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    - curl -LO https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
    - chmod u+x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage
  script:
    - ./linuxdeploy-x86_64.AppImage \
        --executable ${FUBBLE_PREFIX_DIR}/bin/fubble \
        --desktop-file=client/app/fubble.desktop \
        --icon-file=client/app/pics/fubble.svg
        --appdir appdir \
        --plugin qt \
        --output appimage
  artifacts:
    paths:
      - ./*.AppImage
    expire_in: 1 week

build windows release:
  stage: build
  tags:
    - windows
  variables:
    FUBBLE_TREAT_WARNING_AS_ERROR: 0
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
    FUBBLE_BUILD_NINJA_JOBS: '1'
  script:
    - choco install -y --no-progress python pkgconfiglite
    # - refreshenv # did not work
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - python --version
    - pip install conan aqtinstall
    - aqt install --outputdir c:\Qt 5.14.2 windows desktop win64_msvc2017_64
    - conan --version
    - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
    - conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"
    - conan remote add google_webrtc "https://api.bintray.com/conan/freckled/google-webrtc"
    - python scripts/make_build.py
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

