
#include:
#  - local: '/web/landing/.gitlab-ci.yml'

.build debug:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v0
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: "overlay2"
    FUBBLE_TREAT_WARNING_AS_ERROR: 0
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    - ./scripts/ci/build_debug
  after_script:
    - rm -r ./deploy/development/install
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

build windows release:
  stage: build
  tags:
    - windows
  script:
    - choco install python
    - pip3 install conan meson

