
#include:
#  - local: '/web/landing/.gitlab-ci.yml'

.build debug:
  image: registry.gitlab.com/acof/fubble/ci/build_ubuntu_1804:v0
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: "overlay2"
    FUBBLE_TREAT_WARNING_AS_ERROR: 0
    FUBBLE_PREFIX_DIR: ${CI_PROJECT_DIR}/install
  script:
    - ./scripts/ci/build_debug
  after_script:
    - rm -r ./deploy/development/install
    - mv -v ../fubble_build/meson/meson-logs .
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always

build windows release:
  stage: build
  tags:
    - windows
  script:
    - choco install -y --no-progress python
    # - refreshenv # did not work
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - python --version
    - pip install conan
    - conan --version
    - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
    - conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"
    - conan remote add google_webrtc "https://api.bintray.com/conan/freckled/google-webrtc"
    - scripts/make_build.py

