
include:
  - local: '/web/landing/.gitlab-ci.yml'

build debug:
  image: ubuntu:18.04
  stage: build
  variables:
    FUBBLE_TREAT_WARNING_AS_ERROR: 0
  before_script:
    - apt-get update && apt-get install -y fish sudo
  script:
    - ./scripts/install_system_dependencies
    - ./scripts/make_build

