#!/bin/sh

set -e
cd "$(dirname "$0")"

image_name=$CI_REGISTRY_IMAGE/server/session_handler:$CI_COMMIT_REF_NAME

cp -v ../../dist/server-1.0.0-py3-none-any.whl ./package
docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
docker build -t $image_name package
docker push $image_name
