#!/bin/bash

set -e
cd "$(dirname "$0")"/..

proto_dir=../../../proto/
proto_file=web_rtc.proto
result_dir=server
cp $proto_dir/$proto_file $result_dir
python3 -m grpc_tools.protoc \
  -I. \
  --python_out=. \
  --grpc_python_out=. \
  $result_dir/$proto_file
rm $result_dir/$proto_file

