#!/bin/bash

set -e

current_dir="$PWD"
cd "$(dirname "$0")"
source ../environment

# apt-get update
# apt-get install -y fuse \
#    qml-module-qtquick-\* qml-module-qt-labs-\* \
#    qml-module-qtcharts qml-module-qtmultimedia qtdeclarative5-dev-tools

export LD_LIBRARY_PATH=$(realpath $(dirname $(which qmake))/../lib)

cd "$current_dir"
curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
curl -LO https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
chmod u+x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage

export QML_SOURCES_PATHS="${source_dir}/client/app"

mkdir -p appdir/usr
cp -rv "${prefix_dir}/share" appdir/usr
./linuxdeploy-x86_64.AppImage \
    --executable "${prefix_dir}/bin/fubble" \
    --desktop-file="${source_dir}/client/app/fubble.desktop" \
    --icon-file="${source_dir}/client/app/images/fubble.svg" \
    --appdir appdir \
    --plugin qt \
    --output appimage
ln -s Fubble*-x86_64.AppImage Fubble-latest-x86_64.AppImage

