#!/bin/bash -e

current_dir="$PWD"
cd "$(dirname "$0")"
source ../environment


cd "$current_dir"
curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
# if that version gets a bug, use a fixed version from their CI
# curl -LO https://artifacts.assassinate-you.net/artifactory/list/linuxdeploy/travis-456/linuxdeploy-x86_64.AppImage
curl -LO https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
chmod u+x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage

export QML_SOURCES_PATHS="${source_dir}/fubble/app"
export LD_LIBRARY_PATH="$(realpath $(dirname $(which qmake))/../lib)"
export LD_LIBRARY_PATH="${prefix_dir}/lib64:${LD_LIBRARY_PATH}" 

mkdir -p appdir/usr
cp -rv "${prefix_dir}/share" appdir/usr
./linuxdeploy-x86_64.AppImage \
    --executable "${prefix_dir}/bin/fubble" \
    --desktop-file="${source_dir}/fubble/app/fubble.desktop" \
    --icon-file="${source_dir}/fubble/app/images/fubble.svg" \
    --appdir appdir \
    --plugin qt \
    --output appimage
# additional executables are possible, eg:
#     --executable "/usr/bin/addr2line"
# it seems like the first --executable is the entrypoint

ln -s Fubble*-x86_64.AppImage Fubble-latest-x86_64.AppImage

