#!/bin/bash

docker_user=$1
docker_password=$2
docker_image=$3
docker_name=$4

docker login -u $docker_user -p $docker_password registry.gitlab.com \
  || exit 1
docker pull $docker_image || exit 1
docker rm -f $docker_name
docker run -d \
  -p 8080:8080 \
  --restart always \
  --name $docker_name \
  $docker_image \
  || exit 1
