version: '3'

services:
  landing:
    build:
      context: .
      dockerfile: landing/Dockerfile
  signalling:
    build:
      context: .
      dockerfile: signalling/Dockerfile
  temporary_room:
    build:
      context: .
      dockerfile: temporary_room/Dockerfile
    depends_on:
      - synapse
  windows_rclone:
    build:
      context: .
      dockerfile: windows_rclone/Dockerfile
  download:
    build:
      context: .
      dockerfile: download/Dockerfile
  synapse:
    # https://github.com/matrix-org/synapse/blob/master/contrib/docker/docker-compose.yml
    build:
      context: synapse
    environment:
      - SYNAPSE_SERVER_NAME=fubble.io
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - synapse_data:/data
    depends_on:
      - synapse_database
  synapse_database:
    image: docker.io/postgres:latest
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse_database_data:/var/lib/postgresql/data
  proxy:
    build:
      context: proxy
    command: [nginx-debug, '-g', 'daemon off;']
    environment:
      - LETSENCRYPT_EMAIL=contact@freckled.dev
      - LETSENCRYPT_HOST=fubble.io,www.fubble.io
      - VIRTUAL_HOST=fubble.io,www.fubble.io
    depends_on:
      - synapse
      - temporary_room
      - signalling
      - landing
      - windows_rclone
      - download

  ssl-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    depends_on:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    depends_on:
      - ssl-proxy

volumes:
  synapse_data:
  synapse_database_data:
  conf:
  vhost:
  html:
  dhparam:
  certs:

