#!/bin/bash

script_dir="$(dirname "$0")"
source_dir="${script_dir}/.."

conan install \
  --build missing \
  --install-folder . \
  --profile="$script_dir/conan_raspberrypi_config" \
  "$source_dir"


