#!/usr/bin/env fish

set script (status -f)
cd (dirname $script)

if grep -i ubuntu /etc/os-release
  # from webrtc `install-build-deps.sh`
  # only the run packages
  sudo apt-get -qq -y install \
    libappindicator3-1 \
    libasound2 \
    libatk1.0-0 \
    ibatspi2.0-0 \
    libc6 \
    libcairo2 \
    libcap2 \
    libcups2 \
    libexpat1 \
    libfontconfig1 \
    libfreetype6 \
    libglib2.0-0 \
    libgtk-3-0 \
    libpam0g \
    libpango1.0-0 \
    libpci3 \
    libpcre3 \
    libpixman-1-0 \
    libspeechd2 \
    libstdc++6 \
    libsqlite3-0 \
    libuuid1 \
    libwayland-egl1-mesa \
    libx11-6 \
    libx11-xcb1 \
    libxau6 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxdmcp6 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxinerama1 \
    libxrandr2 \
    libxrender1 \
    libxtst6 \
    zlib1g \
    python3-pip python3-setuptools python3-wheel \
    ninja-build g++ libx11-dev libssl-dev ccache \
    qt5-default qttools5-dev-tools qtquickcontrols2-5-dev qtmultimedia5-dev \
    qtdeclarative5-dev libqt5charts5-dev libqt5svg5-dev \
    qml-module-qtmultimedia qml-module-qtcharts \
    pkg-config git fuse rsync rclone curl \
    libxdamage-dev libxcomposite-dev libxtst-dev libxrandr-dev \
    pulseaudio docker.io
  sudo pip3 install --upgrade pip
  sudo -H pip3 install conan meson docker-compose aqtinstall
  conan profile new default --detect
  conan profile update settings.compiler.libcxx=libstdc++11 default
  # cmake
  sudo apt-get -y install gpg wget
  wget -O - "https://apt.kitware.com/keys/kitware-archive-latest.asc" 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
  echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] "https://apt.kitware.com/ubuntu/" bionic main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
  sudo apt-get update
  sudo apt-get install -y cmake
else
  echo "could not determine the operating system"
  cat /etc/os-release
end

