#!/bin/bash

set -e
# set -x
cd "$(dirname "$0")"
source environment
scripts_dir="$(pwd)"

rm -rf $build_dir
mkdir -p $build_dir
cd $build_dir

mkdir -p $dependencies_dir
cd $dependencies_dir
$scripts_dir/get_dependencies_conan

cd $build_dir
# multiple paths with `:`
export PKG_CONFIG_PATH="${dependencies_dir}"
export BOOST_ROOT=$(pkg-config --variable=prefix boost)
echo "set BOOST_ROOT to: $BOOST_ROOT"
if [ -z ${FUBBLE_TREAT_WARNING_AS_ERROR+x} ];
then
  werror='true'
else
  if [[ ${FUBBLE_TREAT_WARNING_AS_ERROR} -eq "0" ]];
  then
    werror='false'
  else
    werror='true'
  fi
fi

# export CC="ccache clang"
# export CXX="ccache clang++"
meson "$source_dir" meson \
  --prefix="$prefix_dir" \
  -Db_sanitize=address \
  -Db_lundef=false \
  -Dwarning_level=3 \
  -Dwerror=$werror

#   --fatal-meson-warnings \
#  -Db_coverage=true \
#  -Ddefault_library=static \

ln -frs meson/compile_commands.json ..
time ninja -C meson

