#!/bin/bash

set -ex
cd "$(dirname "$0")"

scripts_dir="$(pwd)"
source_dir="$(realpath ..)"
project_root_dir="$(git rev-parse --show-toplevel)"
build_dir="$project_root_dir/../fubble_build_raspberrypi"
prefix_dir="$build_dir/install"
dependencies_dir="$build_dir/dependencies"
google_webrtc_dir="$project_root_dir/.."

rm -rf $build_dir
mkdir -p $build_dir
cd $build_dir

mkdir -p $dependencies_dir
cd $dependencies_dir
$scripts_dir/get_dependencies_conan_raspberrypi

cd $build_dir
export PKG_CONFIG_PATH="${dependencies_dir}:${google_webrtc_dir}"
export BOOST_ROOT=$(pkg-config --variable=prefix boost)
# export CC="ccache clang"
# export CXX="ccache clang++"
meson "$source_dir" meson \
  --cross-file="$scripts_dir/meson_raspberrypi_config" \
  --prefix="$prefix_dir" \
  --fatal-meson-warnings \
  -Db_sanitize=address \
  -Db_lundef=false \
  -Dwarning_level=3 \
  -Dwerror=true

#  -Db_coverage=true \
#  -Ddefault_library=static \

# ln -frs meson/compile_commands.json ..
ninja -C meson


