#!/bin/bash

set -ex
cd "$(dirname "$0")"

scripts_dir="$(pwd)"
source_dir="$(realpath ..)"
project_root_dir="$(git rev-parse --show-toplevel)"
build_dir="$project_root_dir/../fubble_build"
prefix_dir="$build_dir/install"
dependencies_dir="$build_dir/dependencies"
google_webrtc_dir="$project_root_dir/../google_webrtc/webrtc-checkout/src"

rm -rf $build_dir
mkdir -p $build_dir
cd $build_dir

mkdir -p $dependencies_dir
cd $dependencies_dir
$scripts_dir/get_dependencies_conan

# generate google webrtc pkg-config file
rdmd $scripts_dir/google-webrtc_pkg-config_generator/source/app.d \
  -s "$google_webrtc_dir" -b "$google_webrtc_dir/out/Default" \
  > "$dependencies_dir/google-webrtc.pc"

cd $build_dir
# multiple paths with `:`
export PKG_CONFIG_PATH="${dependencies_dir}"
export BOOST_ROOT=$(pkg-config --variable=prefix boost)
# export CC="ccache clang"
# export CXX="ccache clang++"
meson "$source_dir" meson \
  --prefix="$prefix_dir" \
  -Db_sanitize=address \
  -Db_lundef=false \
  -Dwarning_level=3 \
  -Dwerror=true

#   --fatal-meson-warnings \
#  -Db_coverage=true \
#  -Ddefault_library=static \

ln -frs meson/compile_commands.json ..
ninja -C meson

