#!/bin/bash

set -x
cd "$(dirname "$0")"

# get diff from https://boringssl-review.googlesource.com/changes/boringssl~28524/revisions/2/patch?zip&path=crypto%2Fx509%2Fx509_test.cc
(
  curl -Lo e6737a8.diff.zip 'https://boringssl-review.googlesource.com/changes/boringssl~28524/revisions/2/patch?zip&path=crypto%2Fx509%2Fx509_test.cc'
  unzip e6737a8.diff.zip
  cd nakama-cpp/third_party/grpc/third_party/boringssl
  git apply ../../../../../e6737a8.diff
)
(
  cd nakama-cpp/third_party/cpprestsdk/Release/libs/websocketpp
  git switch -c develop
  git pull origin develop
)
# change cpp standard in ./nakama-cpp/src/CMakeLists.txt to 17


set -e

conan install \
  --build missing \
  --install-folder . \
  .
# TODO set PKG_CONFIG_PATH to the path of `build/dependencies` of fubble. And get the boost root.
export BOOST_ROOT=/home/mlanner/.conan/data/boost/1.71.0/conan/stable/package/9c0522fd8d127adef8d9d809f74f262131470e66/
# export PKG_CONFIG_PATH="$(pwd)"
# export BOOST_ROOT=$(pkg-config --variable=prefix boost)

(
  cd nakama-cpp/build/linux
  python build_linux.py --so
)
cd ..
ln -rs nakama/nakama-cpp/release/nakama-cpp-sdk

exit 0

mkdir -p nakama-cpp/release/nakama-cpp-sdk/include

conan install \
  --build missing \
  --install-folder . \
  .
export PKG_CONFIG_PATH="$(pwd)"
export BOOST_ROOT=$(pkg-config --variable=prefix boost)
echo $BOOST_ROOT

rm -rf ./build/*
cd build
cmake -G Ninja \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DNAKAMA_SHARED_LIBRARY=ON \
  -DCMAKE_INSTALL_PREFIX=../install \
  ../nakama-cpp/
cmake --build .

